# -*- coding: utf-8 -*-
"""Freeze-derived holdout classification and observation capabilities.

This is a neutral, stdlib-only leaf.  The campaign layer remains responsible
for verifying freeze/protocol authority and durable attempt consumption before
creating the private receipt consumed by this module's private issuer path.

Python code with permission to import private names can construct or invoke
those private hooks; this module does not claim to prevent that.  The boundary
provided here is narrower: no supported public API can issue an observation
token without the campaign ledger's durable-consumption path.
"""
from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass
import threading
from typing import Any

__all__ = (
    "CalibrationObservationCapability",
    "HoldoutObservationAdmission",
    "HoldoutObservationError",
    "MinimalHoldoutSignature",
    "assert_holdout_observation_admitted",
    "assert_issued_holdout_observation",
    "classify_minimal_holdout_signature",
    "normalized_direct_gflags",
    "protected_signatures_from_verified_freeze",
)


class HoldoutObservationError(RuntimeError):
    """A holdout observation request is malformed or not admitted."""


@dataclass(frozen=True, slots=True)
class MinimalHoldoutSignature:
    """Names kept distinct even where the current freeze uses equal strings."""

    freeze_holdout_key: str
    freeze_candidate_id: str
    trial_workload_name: str
    ycsb_rratio: str


@dataclass(frozen=True, slots=True)
class HoldoutObservationAdmission:
    """Attempt-bound identity token; field equality never establishes issuance."""

    freeze_holdout_key: str
    freeze_candidate_id: str
    trial_workload_name: str
    ycsb_rratio: str
    attempt_id: str
    permitted_run_once_calls: int


@dataclass(frozen=True, slots=True)
class CalibrationObservationCapability:
    """Identity-bound capability for the rr20/rr80 calibration path.

    ``sweep_gflags`` contains the exact direct gflags generated by the
    calibrator except for ``ycsb_tuple_num``.  The latter is deliberately
    represented by the records rule below rather than by a frozen snapshot:
    the sweep doubles records and may stop early, while the noise point is
    selected only after saturation analysis.
    """

    attempt_id: str
    env_tag: str
    receipt_sha256: str
    binary_sha256: str
    ycsb_rratio: str
    permitted_run_once_calls: int
    sweep_gflags: tuple[str, ...]
    sweep_reps: int
    noise_reps: int
    start_records: int
    max_records: int
    records_multiplier: int = 2
    numactl: tuple[str, ...] = ()
    timeout_s: float = 120.0
    use_perf: bool = True
    extra_env: tuple[tuple[str, str], ...] = ()
    plan_sha256: str = ""


@dataclass(frozen=True, slots=True)
class _DurableAttemptConsumptionReceipt:
    """Private handoff created only after Unit B's durable ticket consume."""

    attempt_id: str
    permitted_run_once_calls: int


@dataclass(frozen=True, slots=True)
class _CalibrationObservationReceipt:
    """Private handoff created only after the durable calibration marker."""

    attempt_id: str
    env_tag: str
    receipt_sha256: str
    binary_sha256: str
    ycsb_rratio: str
    permitted_run_once_calls: int
    sweep_gflags: tuple[str, ...]
    sweep_reps: int
    noise_reps: int
    start_records: int
    max_records: int
    records_multiplier: int
    numactl: tuple[str, ...]
    timeout_s: float
    use_perf: bool
    extra_env: tuple[tuple[str, str], ...]
    plan_sha256: str


@dataclass(frozen=True, slots=True)
class _IssuedAdmissionState:
    token: HoldoutObservationAdmission
    signature: MinimalHoldoutSignature
    remaining_run_once_calls: int


@dataclass(frozen=True, slots=True)
class _IssuedCalibrationObservationState:
    capability: CalibrationObservationCapability
    phase: str
    remaining_run_once_calls: int
    next_sweep_records: int | None
    current_sweep_records: int | None
    current_sweep_reps: int
    sweep_records: tuple[int, ...]
    noise_records: int | None
    noise_run_once_calls: int


# This neutral table is deliberately freeze-shaped.  It is not production
# authority: every issuance also derives the set from the already-verified
# freeze document supplied by the campaign layer and requires exact equality.
_NEUTRAL_HOLDOUTS: Mapping[str, Mapping[str, Any]] = {
    "rr80": {
        "candidate_id": "H1",
        "ycsb": {"ycsb_rratio": "80"},
    },
    "rr20": {
        "candidate_id": "H2",
        "ycsb": {"ycsb_rratio": "20"},
    },
}

_INDIRECT_GFLAGS = frozenset({"flagfile", "fromenv", "tryfromenv"})
_UINT64_MAX = (1 << 64) - 1


def _require_nonempty_string(value: object, field: str) -> str:
    if not isinstance(value, str) or not value:
        raise HoldoutObservationError(f"invalid verified freeze {field}")
    return value


def _derive_protected_signatures(
    verified_freeze_document: Mapping[str, object],
) -> frozenset[MinimalHoldoutSignature]:
    """Derive signatures solely from a verified freeze's ``holdouts`` map."""

    if not isinstance(verified_freeze_document, Mapping):
        raise HoldoutObservationError("verified freeze document must be a mapping")
    holdouts = verified_freeze_document.get("holdouts")
    if not isinstance(holdouts, Mapping) or not holdouts:
        raise HoldoutObservationError("verified freeze holdouts must be a nonempty mapping")

    signatures: set[MinimalHoldoutSignature] = set()
    ratios: set[str] = set()
    for raw_key, raw_entry in holdouts.items():
        freeze_holdout_key = _require_nonempty_string(raw_key, "holdout key")
        if not isinstance(raw_entry, Mapping):
            raise HoldoutObservationError(
                f"invalid verified freeze holdout entry: {freeze_holdout_key}"
            )
        freeze_candidate_id = _require_nonempty_string(
            raw_entry.get("candidate_id"),
            f"holdouts.{freeze_holdout_key}.candidate_id",
        )
        ycsb = raw_entry.get("ycsb")
        if not isinstance(ycsb, Mapping):
            raise HoldoutObservationError(
                f"invalid verified freeze holdouts.{freeze_holdout_key}.ycsb"
            )
        ratio = _require_nonempty_string(
            ycsb.get("ycsb_rratio"),
            f"holdouts.{freeze_holdout_key}.ycsb.ycsb_rratio",
        )
        if ratio in ratios:
            raise HoldoutObservationError(
                f"ambiguous verified freeze ycsb_rratio: {ratio}"
            )
        ratios.add(ratio)
        signatures.add(MinimalHoldoutSignature(
            freeze_holdout_key=freeze_holdout_key,
            freeze_candidate_id=freeze_candidate_id,
            trial_workload_name=freeze_holdout_key,
            ycsb_rratio=ratio,
        ))
    return frozenset(signatures)


_NEUTRAL_PROTECTED_SIGNATURES = _derive_protected_signatures(
    {"holdouts": _NEUTRAL_HOLDOUTS}
)
_NEUTRAL_BY_RATIO = {
    signature.ycsb_rratio: signature
    for signature in _NEUTRAL_PROTECTED_SIGNATURES
}


def protected_signatures_from_verified_freeze(
    verified_freeze_document: Mapping[str, object],
) -> frozenset[MinimalHoldoutSignature]:
    """Return the production protected set from the fixed neutral table."""

    return _protected_signatures_from_verified_freeze_core(
        verified_freeze_document,
    )


def _protected_signatures_from_verified_freeze_core(
    verified_freeze_document: Mapping[str, object],
    *,
    _neutral_holdouts: Mapping[str, Mapping[str, object]] | None = None,
) -> frozenset[MinimalHoldoutSignature]:
    """Return the protected set, rejecting drift from the neutral known set.

    The caller must first establish that ``verified_freeze_document`` is the
    verified authority document.  This leaf validates the holdout projection
    and fails closed on additions, removals, or binding changes.
    """

    derived = _derive_protected_signatures(verified_freeze_document)
    if _neutral_holdouts is None:
        if derived != _NEUTRAL_PROTECTED_SIGNATURES:
            raise HoldoutObservationError(
                "verified freeze holdout signatures do not exactly match the neutral set"
            )
        return derived
    expected = _derive_protected_signatures({"holdouts": _neutral_holdouts})
    if derived != expected:
        raise HoldoutObservationError(
            "verified freeze holdout signatures do not exactly match the neutral set"
        )
    return derived


def normalized_direct_gflags(gflags: Sequence[str]) -> dict[str, str]:
    """Normalize direct gflags with last-wins semantics.

    Both one- and two-dash forms are accepted.  Inputs that can cause gflags
    to obtain values indirectly are rejected before classification.
    """

    effective: dict[str, str] = {}
    for raw in gflags:
        if type(raw) is not str:
            raise HoldoutObservationError("gflags must contain exact strings only")
        if not raw.startswith("-") or raw == "-":
            continue
        body = raw[2:] if raw.startswith("--") else raw[1:]
        name, separator, value = body.partition("=")
        if name in _INDIRECT_GFLAGS:
            raise HoldoutObservationError(f"indirect gflags input is forbidden: {name}")
        if separator and name:
            effective[name] = value
    ratio = effective.get("ycsb_rratio")
    if ratio is not None:
        if (not ratio or not ratio.isascii() or not ratio.isdecimal()
                or (len(ratio) > 1 and ratio.startswith("0"))):
            raise HoldoutObservationError(
                "ycsb_rratio must be canonical unsigned decimal"
            )
        if int(ratio, 10) > _UINT64_MAX:
            raise HoldoutObservationError("ycsb_rratio exceeds uint64 range")
    return effective


def classify_minimal_holdout_signature(
    gflags: Sequence[str],
) -> MinimalHoldoutSignature | None:
    """Classify the effective direct read ratio against the protected set."""

    effective = normalized_direct_gflags(gflags)
    return _NEUTRAL_BY_RATIO.get(effective.get("ycsb_rratio"))


def _exact_positive_int(value: object, field: str) -> int:
    if type(value) is not int or value <= 0:
        raise HoldoutObservationError(f"{field} must be a positive exact int")
    return value


def _sha256_field(value: object, field: str, *, allow_empty: bool = False) -> str:
    if type(value) is not str or (not allow_empty and not value):
        raise HoldoutObservationError(f"{field} must be a SHA-256 hex string")
    if allow_empty and value == "":
        return value
    if len(value) != 64 or any(ch not in "0123456789abcdef" for ch in value):
        raise HoldoutObservationError(f"{field} must be a SHA-256 hex string")
    return value


def _direct_flag_name_value(raw: object) -> tuple[str, bool, str] | None:
    if type(raw) is not str or not raw.startswith("-") or raw == "-":
        return None
    body = raw[2:] if raw.startswith("--") else raw[1:]
    name, separator, value = body.partition("=")
    return name, bool(separator), value


def _normalize_static_gflags(value: Sequence[str]) -> tuple[str, ...]:
    try:
        flags = tuple(value)
    except TypeError as exc:
        raise HoldoutObservationError("sweep_gflags must be a sequence") from exc
    for raw in flags:
        if type(raw) is not str:
            raise HoldoutObservationError("sweep_gflags must contain exact strings only")
        parsed = _direct_flag_name_value(raw)
        if parsed is not None and parsed[0] == "ycsb_tuple_num":
            raise HoldoutObservationError(
                "sweep_gflags must omit the dynamic ycsb_tuple_num flag"
            )
    effective = normalized_direct_gflags(flags)
    if "ycsb_tuple_num" in effective:
        raise HoldoutObservationError(
            "sweep_gflags must omit the dynamic ycsb_tuple_num flag"
        )
    return flags


def _normalize_numactl(value: Sequence[str] | None) -> tuple[str, ...]:
    if value is None:
        return ()
    try:
        result = tuple(value)
    except TypeError as exc:
        raise HoldoutObservationError("numactl must be a sequence") from exc
    if any(type(item) is not str for item in result):
        raise HoldoutObservationError("numactl must contain exact strings only")
    return result


def _normalize_extra_env(
    value: Mapping[str, str] | Sequence[tuple[str, str]] | None,
) -> tuple[tuple[str, str], ...]:
    if value is None:
        return ()
    items = value.items() if isinstance(value, Mapping) else value
    try:
        result = tuple(items)
    except TypeError as exc:
        raise HoldoutObservationError("extra_env must be a string mapping") from exc
    normalized: list[tuple[str, str]] = []
    for item in result:
        if (not isinstance(item, Sequence) or len(item) != 2
                or type(item[0]) is not str or type(item[1]) is not str):
            raise HoldoutObservationError("extra_env must be a string mapping")
        normalized.append((item[0], item[1]))
    return tuple(sorted(normalized))


def _normalize_timeout(value: object, field: str = "timeout_s") -> float:
    if type(value) not in (int, float):
        raise HoldoutObservationError(f"{field} must be a positive finite number")
    normalized = float(value)
    if (normalized <= 0 or normalized != normalized
            or normalized in (float("inf"), float("-inf"))):
        raise HoldoutObservationError(f"{field} must be a positive finite number")
    return normalized


def _number_of_sweep_points(
    start_records: int, max_records: int, records_multiplier: int,
) -> int:
    points = 0
    records = start_records
    while records <= max_records:
        points += 1
        records *= records_multiplier
    return points


def _validate_calibration_plan(
    *,
    attempt_id: object,
    env_tag: object,
    receipt_sha256: object,
    binary_sha256: object,
    ycsb_rratio: object,
    permitted_run_once_calls: object,
    sweep_gflags: Sequence[str],
    sweep_reps: object,
    noise_reps: object,
    start_records: object,
    max_records: object,
    records_multiplier: object = 2,
    numactl: Sequence[str] | None = None,
    timeout_s: object = 120.0,
    use_perf: object = True,
    extra_env: Mapping[str, str] | Sequence[tuple[str, str]] | None = None,
    plan_sha256: object = "",
) -> dict[str, object]:
    for value, field in ((attempt_id, "attempt_id"), (env_tag, "env_tag")):
        if type(value) is not str or not value:
            raise HoldoutObservationError(f"{field} must be a nonempty exact str")
    receipt_hash = _sha256_field(receipt_sha256, "receipt_sha256")
    binary_hash = _sha256_field(binary_sha256, "binary_sha256")
    plan_hash = _sha256_field(plan_sha256, "plan_sha256", allow_empty=True)
    if type(ycsb_rratio) is not str or ycsb_rratio not in _NEUTRAL_BY_RATIO:
        raise HoldoutObservationError(
            "calibration capability is only available for protected rr20/rr80"
        )
    permitted = _exact_positive_int(
        permitted_run_once_calls, "permitted_run_once_calls")
    sweep_reps_value = _exact_positive_int(sweep_reps, "sweep_reps")
    noise_reps_value = _exact_positive_int(noise_reps, "noise_reps")
    start_value = _exact_positive_int(start_records, "start_records")
    max_value = _exact_positive_int(max_records, "max_records")
    multiplier = _exact_positive_int(records_multiplier, "records_multiplier")
    if multiplier != 2:
        raise HoldoutObservationError(
            "records_multiplier must match the calibrator doubling rule")
    if start_value > max_value:
        raise HoldoutObservationError("start_records must not exceed max_records")
    static_flags = _normalize_static_gflags(sweep_gflags)
    effective = normalized_direct_gflags(static_flags)
    if effective.get("ycsb_rratio") != ycsb_rratio:
        raise HoldoutObservationError(
            "sweep_gflags ycsb_rratio does not match the capability")
    expected_calls = (
        _number_of_sweep_points(start_value, max_value, multiplier)
        * sweep_reps_value + noise_reps_value
    )
    if permitted != expected_calls:
        raise HoldoutObservationError(
            "permitted_run_once_calls does not match the sweep/noise plan")
    if type(use_perf) is not bool:
        raise HoldoutObservationError("use_perf must be an exact bool")
    return {
        "attempt_id": attempt_id,
        "env_tag": env_tag,
        "receipt_sha256": receipt_hash,
        "binary_sha256": binary_hash,
        "ycsb_rratio": ycsb_rratio,
        "permitted_run_once_calls": permitted,
        "sweep_gflags": static_flags,
        "sweep_reps": sweep_reps_value,
        "noise_reps": noise_reps_value,
        "start_records": start_value,
        "max_records": max_value,
        "records_multiplier": multiplier,
        "numactl": _normalize_numactl(numactl),
        "timeout_s": _normalize_timeout(timeout_s),
        "use_perf": use_perf,
        "extra_env": _normalize_extra_env(extra_env),
        "plan_sha256": plan_hash,
    }


def _split_runtime_gflags(
    gflags: Sequence[str],
) -> tuple[int, tuple[str, ...]]:
    records: list[int] = []
    static: list[str] = []
    for raw in gflags:
        if type(raw) is not str:
            raise HoldoutObservationError("gflags must contain exact strings only")
        parsed = _direct_flag_name_value(raw)
        if parsed is not None and parsed[0] == "ycsb_tuple_num":
            if not parsed[1] or not parsed[2].isdecimal():
                raise HoldoutObservationError(
                    "ycsb_tuple_num must be a canonical positive decimal")
            value = int(parsed[2], 10)
            if value <= 0 or str(value) != parsed[2]:
                raise HoldoutObservationError(
                    "ycsb_tuple_num must be a canonical positive decimal")
            records.append(value)
        else:
            static.append(raw)
    if len(records) != 1:
        raise HoldoutObservationError(
            "calibration gflags must contain exactly one ycsb_tuple_num")
    return records[0], tuple(static)


def _identity_calibration_capability_functions():
    """Keep calibration receipts and capabilities in a registry separate from formal tokens."""

    receipts: dict[int, _CalibrationObservationReceipt] = {}
    issued: dict[int, _IssuedCalibrationObservationState] = {}
    lock = threading.RLock()

    def new_receipt(**kwargs) -> _CalibrationObservationReceipt:
        values = _validate_calibration_plan(**kwargs)
        receipt = _CalibrationObservationReceipt(**values)
        with lock:
            receipts[id(receipt)] = receipt
        return receipt

    def issue_from_receipt(
        *, receipt: _CalibrationObservationReceipt,
    ) -> CalibrationObservationCapability:
        if not isinstance(receipt, _CalibrationObservationReceipt):
            raise HoldoutObservationError(
                "calibration observation receipt was not issued")
        with lock:
            registered = receipts.pop(id(receipt), None)
            if registered is None or registered is not receipt:
                raise HoldoutObservationError(
                    "calibration observation receipt was not issued or was reused"
                )
            capability = CalibrationObservationCapability(
                attempt_id=receipt.attempt_id,
                env_tag=receipt.env_tag,
                receipt_sha256=receipt.receipt_sha256,
                binary_sha256=receipt.binary_sha256,
                ycsb_rratio=receipt.ycsb_rratio,
                permitted_run_once_calls=receipt.permitted_run_once_calls,
                sweep_gflags=receipt.sweep_gflags,
                sweep_reps=receipt.sweep_reps,
                noise_reps=receipt.noise_reps,
                start_records=receipt.start_records,
                max_records=receipt.max_records,
                records_multiplier=receipt.records_multiplier,
                numactl=receipt.numactl,
                timeout_s=receipt.timeout_s,
                use_perf=receipt.use_perf,
                extra_env=receipt.extra_env,
                plan_sha256=receipt.plan_sha256,
            )
            issued[id(capability)] = _IssuedCalibrationObservationState(
                capability=capability,
                phase="sweep",
                remaining_run_once_calls=capability.permitted_run_once_calls,
                next_sweep_records=capability.start_records,
                current_sweep_records=None,
                current_sweep_reps=0,
                sweep_records=(),
                noise_records=None,
                noise_run_once_calls=0,
            )
        return capability

    def assert_issued(capability: object) -> None:
        with lock:
            state = issued.get(id(capability))
        if state is None or state.capability is not capability:
            raise HoldoutObservationError(
                "calibration observation capability was not issued")

    def transition_to_noise(
        capability: object, *, saturation_records: int,
    ) -> None:
        if type(saturation_records) is not int or saturation_records <= 0:
            raise HoldoutObservationError("saturation records must be positive exact int")
        with lock:
            state = issued.get(id(capability))
            if state is None or state.capability is not capability:
                raise HoldoutObservationError(
                    "calibration observation capability was not issued")
            if state.phase != "sweep":
                raise HoldoutObservationError(
                    "calibration observation capability phase transition is not allowed")
            if state.current_sweep_reps != 0:
                raise HoldoutObservationError(
                    "sweep phase was not consumed at a repetition boundary")
            if state.next_sweep_records is not None:
                raise HoldoutObservationError(
                    "sweep phase still has unconsumed records")
            if saturation_records not in state.sweep_records:
                raise HoldoutObservationError(
                    "noise records were not observed during the sweep phase")
            issued[id(capability)] = _IssuedCalibrationObservationState(
                capability=state.capability,
                phase="noise",
                remaining_run_once_calls=state.remaining_run_once_calls,
                next_sweep_records=state.next_sweep_records,
                current_sweep_records=state.current_sweep_records,
                current_sweep_reps=state.current_sweep_reps,
                sweep_records=state.sweep_records,
                noise_records=saturation_records,
                noise_run_once_calls=0,
            )

    def consume_run_once(
        capability: object,
        *,
        gflags: Sequence[str],
        phase: str | None,
        binary_sha256: str | None,
        numactl: Sequence[str] | None,
        timeout_s: object,
        use_perf: object,
        extra_env: Mapping[str, str] | Sequence[tuple[str, str]] | None,
    ) -> tuple[tuple[str, ...], tuple[tuple[str, str], ...]]:
        records, static_flags = _split_runtime_gflags(gflags)
        # This second normalization is intentional: it rejects indirect values
        # even when a caller happened to construct a matching static tuple.
        normalized_direct_gflags(gflags)
        actual_binary_hash = _sha256_field(binary_sha256, "binary_sha256")
        actual_numactl = _normalize_numactl(numactl)
        actual_timeout = _normalize_timeout(timeout_s)
        actual_extra_env = _normalize_extra_env(extra_env)
        if type(use_perf) is not bool:
            raise HoldoutObservationError("use_perf must be an exact bool")

        with lock:
            state = issued.get(id(capability))
            if state is None or state.capability is not capability:
                raise HoldoutObservationError(
                    "calibration observation capability was not issued")
            expected = state.capability
            if actual_binary_hash != expected.binary_sha256:
                raise HoldoutObservationError(
                    "calibration binary hash does not match the capability")
            if static_flags != expected.sweep_gflags:
                raise HoldoutObservationError(
                    "calibration gflags do not match the capability")
            if actual_numactl != expected.numactl:
                raise HoldoutObservationError(
                    "calibration numactl does not match the capability")
            if actual_timeout != expected.timeout_s:
                raise HoldoutObservationError(
                    "calibration timeout does not match the capability")
            if use_perf is not expected.use_perf:
                raise HoldoutObservationError(
                    "calibration perf mode does not match the capability")
            if actual_extra_env != expected.extra_env:
                raise HoldoutObservationError(
                    "calibration environment does not match the capability")
            if state.remaining_run_once_calls <= 0:
                raise HoldoutObservationError(
                    "calibration observation capability run_once allowance exhausted")
            if phase == "sweep":
                if state.phase != "sweep":
                    raise HoldoutObservationError(
                        "sweep phase is no longer active")
                if state.next_sweep_records is None:
                    raise HoldoutObservationError(
                        "sweep records allowance is exhausted")
                if records != state.next_sweep_records:
                    raise HoldoutObservationError(
                        "sweep records do not follow the capability doubling rule")
                next_reps = state.current_sweep_reps + 1
                if next_reps > expected.sweep_reps:
                    raise HoldoutObservationError(
                        "sweep repetition count exceeds the capability")
                if next_reps == expected.sweep_reps:
                    next_records = records * expected.records_multiplier
                    if next_records > expected.max_records:
                        next_records = None
                    new_state = _IssuedCalibrationObservationState(
                        capability=expected,
                        phase="sweep",
                        remaining_run_once_calls=state.remaining_run_once_calls - 1,
                        next_sweep_records=next_records,
                        current_sweep_records=None,
                        current_sweep_reps=0,
                        sweep_records=state.sweep_records + (records,),
                        noise_records=None,
                        noise_run_once_calls=0,
                    )
                else:
                    new_state = _IssuedCalibrationObservationState(
                        capability=expected,
                        phase="sweep",
                        remaining_run_once_calls=state.remaining_run_once_calls - 1,
                        next_sweep_records=state.next_sweep_records,
                        current_sweep_records=records,
                        current_sweep_reps=next_reps,
                        sweep_records=state.sweep_records,
                        noise_records=None,
                        noise_run_once_calls=0,
                    )
            elif phase == "noise":
                if state.phase != "noise":
                    raise HoldoutObservationError(
                        "noise phase requires a completed sweep phase")
                if records != state.noise_records:
                    raise HoldoutObservationError(
                        "noise records do not match the completed sweep saturation")
                if state.noise_run_once_calls >= expected.noise_reps:
                    raise HoldoutObservationError(
                        "noise repetition count exceeds the capability")
                new_state = _IssuedCalibrationObservationState(
                    capability=expected,
                    phase="noise",
                    remaining_run_once_calls=state.remaining_run_once_calls - 1,
                    next_sweep_records=state.next_sweep_records,
                    current_sweep_records=state.current_sweep_records,
                    current_sweep_reps=state.current_sweep_reps,
                    sweep_records=state.sweep_records,
                    noise_records=state.noise_records,
                    noise_run_once_calls=state.noise_run_once_calls + 1,
                )
            else:
                raise HoldoutObservationError(
                    "calibration observation phase must be sweep or noise")
            issued[id(capability)] = new_state
        return actual_numactl, actual_extra_env

    return new_receipt, issue_from_receipt, assert_issued, transition_to_noise, consume_run_once


(
    _new_calibration_observation_receipt,
    _issue_calibration_observation_capability_from_receipt,
    _assert_issued_calibration_observation,
    _transition_calibration_observation_to_noise,
    _consume_calibration_observation_run_once,
) = _identity_calibration_capability_functions()
del _identity_calibration_capability_functions


def _identity_capability_functions():
    # Keep the strong-reference registry in a closure: importing a private
    # module name cannot expose a seal or mutable registry that forges identity.
    issued: dict[int, _IssuedAdmissionState] = {}
    receipts: dict[int, _DurableAttemptConsumptionReceipt] = {}
    lock = threading.RLock()

    def new_receipt(
        *, attempt_id: str, permitted_run_once_calls: int,
    ) -> _DurableAttemptConsumptionReceipt:
        """Register Unit B's private post-durable-consumption handoff.

        This private Python hook is a supported-layer boundary, not a sandbox:
        code allowed to import private names can call it without doing I/O.
        """
        if type(attempt_id) is not str or not attempt_id:
            raise HoldoutObservationError("attempt_id must be a nonempty exact str")
        if (type(permitted_run_once_calls) is not int
                or permitted_run_once_calls <= 0):
            raise HoldoutObservationError(
                "permitted_run_once_calls must be a positive exact int"
            )
        receipt = _DurableAttemptConsumptionReceipt(
            attempt_id=attempt_id,
            permitted_run_once_calls=permitted_run_once_calls,
        )
        with lock:
            receipts[id(receipt)] = receipt
        return receipt

    def issue_from_receipt(
        *,
        receipt: _DurableAttemptConsumptionReceipt,
        verified_freeze_document: Mapping[str, object],
        freeze_holdout_key: str,
        _neutral_holdouts: Mapping[str, Mapping[str, object]] | None = None,
    ) -> HoldoutObservationAdmission:
        """Consume one private receipt and issue its attempt-bound token."""
        signatures = _protected_signatures_from_verified_freeze_core(
            verified_freeze_document,
            _neutral_holdouts=_neutral_holdouts,
        )
        matches = [
            signature for signature in signatures
            if signature.freeze_holdout_key == freeze_holdout_key
        ]
        if len(matches) != 1:
            raise HoldoutObservationError(
                f"verified freeze holdout key is not protected: {freeze_holdout_key}"
            )
        with lock:
            registered_receipt = receipts.pop(id(receipt), None)
            if registered_receipt is None or registered_receipt is not receipt:
                raise HoldoutObservationError(
                    "durable attempt consumption receipt was not issued or was reused"
                )
            signature = matches[0]
            token = HoldoutObservationAdmission(
                freeze_holdout_key=signature.freeze_holdout_key,
                freeze_candidate_id=signature.freeze_candidate_id,
                trial_workload_name=signature.trial_workload_name,
                ycsb_rratio=signature.ycsb_rratio,
                attempt_id=receipt.attempt_id,
                permitted_run_once_calls=receipt.permitted_run_once_calls,
            )
            issued[id(token)] = _IssuedAdmissionState(
                token=token,
                signature=signature,
                remaining_run_once_calls=receipt.permitted_run_once_calls,
            )
        return token

    def assert_issued(
        admission: object,
        *,
        expected_signature: MinimalHoldoutSignature | None = None,
    ) -> None:
        with lock:
            state = issued.get(id(admission))
        if state is None or state.token is not admission:
            raise HoldoutObservationError("holdout observation admission was not issued")
        if expected_signature is not None and state.signature != expected_signature:
            raise HoldoutObservationError(
                "holdout observation admission does not match the protected signature"
            )

    def consume_run_once(
        admission: object,
        *,
        effective_ycsb_rratio: str | None,
    ) -> None:
        with lock:
            state = issued.get(id(admission))
            if state is None or state.token is not admission:
                raise HoldoutObservationError(
                    "holdout observation admission was not issued"
                )
            if state.signature.ycsb_rratio != effective_ycsb_rratio:
                raise HoldoutObservationError(
                    "holdout observation admission does not match the protected signature"
                )
            if state.remaining_run_once_calls <= 0:
                raise HoldoutObservationError(
                    "holdout observation admission run_once allowance exhausted"
                )
            issued[id(admission)] = _IssuedAdmissionState(
                token=state.token,
                signature=state.signature,
                remaining_run_once_calls=state.remaining_run_once_calls - 1,
            )

    return new_receipt, issue_from_receipt, assert_issued, consume_run_once


(
    _new_durable_attempt_consumption_receipt,
    _issue_holdout_observation_admission_from_receipt,
    assert_issued_holdout_observation,
    _consume_holdout_observation_run_once,
) = _identity_capability_functions()
del _identity_capability_functions


def assert_holdout_observation_admitted(
    *,
    gflags: Sequence[str],
    admission: HoldoutObservationAdmission | None,
    calibration_observation_capability: CalibrationObservationCapability | None = None,
    calibration_observation_phase: str | None = None,
    binary_sha256: str | None = None,
    numactl: Sequence[str] | None = None,
    timeout_s: object = 120.0,
    use_perf: object = True,
    extra_env: Mapping[str, str] | Sequence[tuple[str, str]] | None = None,
) -> tuple[tuple[str, ...], tuple[tuple[str, str], ...]] | None:
    """Apply the subprocess gateway gate for the effective direct flags.

    Tokenless calls use the fixed production table.  An issued token carries
    the exact verified signature used by its private campaign reservation, so
    the subprocess edge compares the executed ratio with that same signature.
    Calibration calls return the normalized ``numactl`` and ``extra_env``
    values that were consumed by the capability check, so callers can pass
    those snapshots to the subprocess without rereading caller objects.
    """

    if admission is not None and calibration_observation_capability is not None:
        raise HoldoutObservationError(
            "formal admission and calibration capability cannot be combined")
    gflags_snapshot = tuple(gflags)
    effective = normalized_direct_gflags(gflags_snapshot)
    ratio = effective.get("ycsb_rratio")
    if calibration_observation_capability is not None:
        return _consume_calibration_observation_run_once(
            calibration_observation_capability,
            gflags=gflags_snapshot,
            phase=calibration_observation_phase,
            binary_sha256=binary_sha256,
            numactl=numactl,
            timeout_s=timeout_s,
            use_perf=use_perf,
            extra_env=extra_env,
        )
    if admission is None:
        signature = _NEUTRAL_BY_RATIO.get(ratio)
        if signature is not None:
            raise HoldoutObservationError(
                "holdout observation admission required for "
                f"ycsb_rratio={signature.ycsb_rratio}"
            )
        return None
    _consume_holdout_observation_run_once(
        admission,
        effective_ycsb_rratio=ratio,
    )
    return None
